// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlhwbyioedbmrshjqekc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsaHdieWlvZWRibXJzaGpxZWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTU4NDYsImV4cCI6MjA2ODYzMTg0Nn0.34jVQ-xmBVNFEZ7ejif-5afcuXV71TZpubGxMySaTXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});